# Generated by Django 2.2.1 on 2019-09-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='assignee',
        ),
    ]
